---
- name: Renew & replace VaaS certs expiring in ≤ 7 days
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # === Required ===
    vaas_api_key: "{{ venafi_api_key }}"
    tenant_base_url: "https://eval-85300634.venafi.cloud"
    global_api_url:  "https://api.venafi.cloud"

    # === Tuning ===
    page_size: 1000
    poll_interval_sec: 5
    poll_timeout_sec: 180
    # issuing_template_id_override: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

    # === Work dir on controller ===
    work_dir: "/tmp/vaas_day7_or_less"

    # === Optional Linux deployment ===
    deploy_enabled: false
    deploy_group: "tls_targets"
    deploy_cert_path: "/etc/pki/tls/certs/{{ item.subjectCN[0] }}.crt"
    deploy_key_path:  "/etc/pki/tls/private/{{ item.subjectCN[0] }}.key"
    service_to_reload: ""      # e.g. "nginx" | "httpd" (blank = skip)

  pre_tasks:
    - name: Ensure working dir exists
      ansible.builtin.file:
        path: "{{ work_dir }}"
        state: directory
        mode: "0700"

    - name: Assert API key present
      ansible.builtin.assert:
        that:
          - vaas_api_key is defined
          - vaas_api_key | length > 0
        fail_msg: "Set venafi_api_key (AAP var/credential)."

  tasks:
    # 1) Gather certs
    - name: Get certificates (paged up to {{ page_size }})
      ansible.builtin.uri:
        url: "{{ global_api_url }}/outagedetection/v1/certificates?ownershipTree=false&excludeSupersededInstances=false&limit={{ page_size }}"
        method: GET
        headers:
          accept: "application/json"
          tppl-api-key: "{{ vaas_api_key }}"
        return_content: true
        status_code: 200
      register: cert_page

    - name: Parse certs
      ansible.builtin.set_fact:
        all_certs: "{{ (cert_page.json | default(cert_page.content | from_json)).certificates | default([]) }}"

    - name: Compute now (UTC)
      ansible.builtin.set_fact:
        now_iso: "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%SZ') }}"

    # 2) Build list of certs expiring in ≤ 7 days (no json_query)
    - name: Init expiring_soon
      ansible.builtin.set_fact:
        expiring_soon: []

    - name: Append certs expiring in ≤ 7 days
      ansible.builtin.set_fact:
        expiring_soon: "{{ expiring_soon + [ item | combine({'days_left': days_left}) ] }}"
      vars:
        days_left: "{{ ((item.validTo | to_datetime) - (now_iso | to_datetime)).days }}"
      loop: "{{ all_certs }}"
      when:
        - item.validTo is defined
        - days_left >= 0
        - days_left <= 7

    - name: Preview expiring soon (sorted)
      ansible.builtin.debug:
        msg: "{{ expiring_soon | sort(attribute='days_left') | map(attribute='certificateName') | list }}"

    - name: Stop if nothing to renew
      ansible.builtin.meta: end_play
      when: expiring_soon | length == 0

    # 3) Load applications to map applicationId -> issuing template IDs
    - name: Get Applications (with issuing templates)
      ansible.builtin.uri:
        url: "{{ global_api_url }}/outagedetection/v1/applications?ownerDetails=false&ownershipCheck=false&issuingTemplateAssigned=true&ownershipTree=false"
        method: GET
        headers:
          accept: "application/json"
          tppl-api-key: "{{ vaas_api_key }}"
        return_content: true
        status_code: 200
      register: apps_raw

    - name: Build app lookup
      ansible.builtin.set_fact:
        apps_parsed: "{{ apps_raw.json | default(apps_raw.content | from_json) }}"
        apps_by_id: "{{ dict((apps_parsed.applications | default([])) | map(attribute='id') | zip(apps_parsed.applications | default([]))) }}"

    # 4) Renew each expiring cert (loop include)
    - name: Renew each expiring cert (≤ 7 days)
      ansible.builtin.include_tasks: renew_one.yml
      loop: "{{ expiring_soon }}"
      loop_control:
        loop_var: cert_item
      rescue:
        - ansible.builtin.debug:
            msg: "At least one renewal failed; see prior errors."
