- name: venafi_certificate_cloud
  connection: local
  hosts: localhost
  vars:
    # injected via custom credential or set in extra_vars at run time
    venafi_api_key: "{{ venafi_api_key | default(lookup('env','VENAFI_APIKEY'), true) }}"
    venafi_zone:    "{{ venafi_zone    | default('MyApp\\Default') }}"

    # certificate request parameters
    common_name: "www.example.com"
    dns_sans:
      - "www.example.com"
      - "example.com"
    key_type: "rsa"
    key_length: 2048
    cert_dest_path: "/etc/pki/tls/certs/www.example.com.crt"
    key_dest_path:  "/etc/pki/tls/private/www.example.com.key"
    chain_dest_path: "/etc/pki/tls/certs/www.example.com.chain.crt"
    restart_handler: "restart nginx"

  tags:
    - cloud
  tasks:
  - name: venafi_certificate
    venafi.machine_identity.venafi_certificate:
      token: "{{ venafi_api_key | default(lookup('env','VENAFI_APIKEY'), true) }}"
      zone: 'Default'
      cert_path: '/tmp'
      common_name: 'testcert-cloud.example.com'
    register: certout
  - name: dump test output
    debug:
      msg: '{{ certout }}'