- name: venafi_certificate_cloud
  connection: local
  hosts: localhost
  tags:
    - cloud
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      token: "{{ venafi_api_key | default(lookup('env','VENAFI_APIKEY'), true) }}"
      zone: 'Default'
      cert_path: '/tmp'
      common_name: 'testcert-cloud.example.com'
    register: certout
  - name: dump test output
    debug:
      msg: '{{ certout }}'