---
# venafi_certificate_cloud.yml
# AAP 2.5-friendly: no external openssl binary required

- name: venafi_certificate_cloud (local CSR, crypto modules)
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

- collections:
    - community.crypto
    - venafi.machine_identity


  vars:
    # Provide via Credential or Extra Vars (ENV fallback for quick tests)
    venafi_api_key: "{{ venafi_api_key | default(lookup('env','VENAFI_APIKEY'), true) }}"
    venafi_zone:    "{{ venafi_zone    | default('MyApp\\Default') }}"

    # Cert request parameters (override via Survey/Extra Vars)
    common_name: "www.example.com"
    dns_sans:
      - "www.example.com"
      - "example.com"

    # RHEL-style paths
    key_dest_path:   "/etc/pki/tls/private/{{ common_name }}.key"
    csr_dest_path:   "/etc/pki/tls/csr/{{ common_name }}.csr"
    cert_dest_path:  "/etc/pki/tls/certs/{{ common_name }}.crt"
    chain_dest_path: "/etc/pki/tls/certs/{{ common_name }}-chain.crt"

    # Optional: restart a service after issuance/renewal
    restart_handler: "restart nginx"

  pre_tasks:
    - name: Ensure PKI directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "/etc/pki/tls/private"
        - "/etc/pki/tls/csr"
        - "/etc/pki/tls/certs"

  tasks:
    - name: Generate private key (RSA 2048) - no external openssl
      community.crypto.openssl_privatekey:
        path: "{{ key_dest_path }}"
        type: rsa
        size: 2048
        mode: "0600"

    - name: Generate CSR with SANs - no external openssl
      community.crypto.openssl_csr:
        path: "{{ csr_dest_path }}"
        privatekey_path: "{{ key_dest_path }}"
        common_name: "{{ common_name }}"
        # List of SANs like ["DNS:foo","DNS:bar"]
        subject_alt_name: "{{ dns_sans | map('regex_replace','^(.*)$','DNS:\\1') | list }}"
        mode: "0644"

    - name: Request/Renew certificate from Venafi (local CSR; explicit paths)
      venafi.machine_identity.venafi_certificate:
        token: "{{ venafi_api_key }}"
        zone:  "{{ venafi_zone }}"
        common_name: "{{ common_name }}"

        csr_origin: local
        privatekey_path: "{{ key_dest_path }}"
        csr_path:       "{{ csr_dest_path }}"

        # Work around collection alias quirks by setting both
        path:      "{{ cert_dest_path }}"
        cert_path: "{{ cert_dest_path }}"

        chain_option: last
        chain_path: "{{ chain_dest_path }}"

        # Safe to include even with CSR; ignored by some versions, used by others
        alt_name: "{{ dns_sans | map('regex_replace','^(.*)$','DNS:\\1') | join(',') }}"

        unsafe_writes: true
      register: certout
      notify: "{{ restart_handler }}"

    - name: Show module result
      ansible.builtin.debug:
        var: certout

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
