---
# Playbook: renew_expiring_in_3_days_and_deploy.yml
# Purpose:
# - Find ACTIVE certs in Venafi TLS Protect Cloud (VaaS) that expire in ≤ 3 days
# - Issue fresh certs (using venafi_certificate) and stage them on the controller
# - Deploy key/cert/chain to your RHEL9 AWS hosts in group "aws_ec2"

# ----------------------
# PLAY 1: Search + Issue
# ----------------------
- name: Renew certs expiring in ≤ 3 days and stage on controller
  hosts: localhost
  gather_facts: false
  collections:
    - venafi.machine_identity

  vars:
    # === Required ===
    vaas_api_key: "{{ venafi_api_key }}"
    vaas_api_url: "https://api.venafi.cloud"
    # Zone is Application\IssuingTemplate (escape backslash in YAML)
    zone: "AAP25DemoCrt\\AAP25DemoCertAPI"

    # === Tuning ===
    page_size: 1000
    work_dir: "/tmp/vaas_expiring3"

    # Optional: override CN to a fixed name (normally reuse CN from each expiring cert)
    # override_common_name: "app.internal.example"

  pre_tasks:
    - name: Ensure working dir exists
      ansible.builtin.file:
        path: "{{ work_dir }}"
        state: directory
        mode: "0700"

    - name: Assert API key present
      ansible.builtin.assert:
        that:
          - vaas_api_key is defined
          - vaas_api_key | length > 0
        fail_msg: "Set venafi_api_key (AAP var/credential)."

  tasks:
    - name: Compute search window (UTC)
      ansible.builtin.set_fact:
        now_iso: "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%SZ') }}"
        plus3_iso: "{{ lookup('pipe','date -u -d +3days +%Y-%m-%dT%H:%M:%SZ') }}"

    - name: Search expiring (ACTIVE) certs via VaaS certificatesearch
      ansible.builtin.uri:
        url: "{{ vaas_api_url }}/outagedetection/v1/certificatesearch"
        method: POST
        headers:
          accept: "application/json"
          tppl-api-key: "{{ vaas_api_key }}"
        body_format: json
        body:
          expression:
            operator: AND          # <-- REQUIRED (fixes your 503)
            operands:
              - field: "certificateStatus"
                operator: "EQ"
                value: "ACTIVE"
              - field: "validityEnd"
                operator: "GTE"
                value: "{{ now_iso }}"
              - field: "validityEnd"
                operator: "LTE"
                value: "{{ plus3_iso }}"
          ordering:
            orders:
              - field: "validityEnd"
                direction: "ASC"
          paging:
            pageNumber: 0
            pageSize: "{{ page_size | int }}"   # <-- keep numeric
        status_code: 200
        return_content: true
      register: cert_page
      retries: 3
      delay: 2
      until: cert_page.status == 200

    - name: Build expiring list
      ansible.builtin.set_fact:
        expiring_soon: "{{ (cert_page.json | default(cert_page.content | from_json)).certificates | default([]) }}"

    - name: Stop if nothing to renew
      ansible.builtin.meta: end_play
      when: expiring_soon | length == 0

    # Issue new certs using the Ansible module (generates key+CSR, picks up cert)
    - name: Issue new certs via venafi_certificate (pickup=true)
      venafi.machine_identity.venafi_certificate:
        connection: cloud
        url: "{{ vaas_api_url }}"
        token: "{{ vaas_api_key }}"
        zone: "{{ zone }}"
        # Use CN from expiring cert unless override_common_name is provided
        common_name: "{{ override_common_name | default(item.subjectCN[0], true) }}"
        # SANs: include CN plus any DNS SANs from the existing cert (if present)
        san_dns: >-
          {{
            ([override_common_name | default(item.subjectCN[0], true)] +
             (item.subjectAlternativeNamesByType.dNSName | default([])))
            | unique
          }}
        algorithm: "RSA"
        key_size: 2048
        chain_option: "RootFirst"
        pickup: true
        timeout: 300
        state: present
        privatekey_path:  "{{ work_dir }}/{{ item.subjectCN[0] }}.key"
        certificate_path: "{{ work_dir }}/{{ item.subjectCN[0] }}.crt"
        chain_path:       "{{ work_dir }}/{{ item.subjectCN[0] }}-chain.crt"
      loop: "{{ expiring_soon }}"
      loop_control:
        label: "{{ item.subjectCN[0] }}"

# ----------------------
# PLAY 2: Deploy to VMs
# ----------------------
- name: Deploy renewed certs to RHEL9 AWS instances
  hosts: aws_ec2
  become: true
  gather_facts: false
  vars:
    # Pull data staged by Play 1
    work_dir_ctrl: "{{ hostvars['localhost']['work_dir'] }}"
    expiring_list: "{{ hostvars['localhost']['expiring_soon'] }}"
    # Destination paths on the VMs (key/cert) + chain into trust (optional)
    cert_dest:  "/etc/pki/tls/certs/{{ item.subjectCN[0] }}.crt"
    key_dest:   "/etc/pki/tls/private/{{ item.subjectCN[0] }}.key"
    chain_dest: "/etc/pki/ca-trust/source/anchors/{{ item.subjectCN[0] }}-chain.crt"
    # Set a service to reload if you want, e.g., nginx | httpd | haproxy (blank = skip)
    service_to_reload: ""

  tasks:
    - name: Ensure destination dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "/etc/pki/tls/certs"
        - "/etc/pki/tls/private"
        - "/etc/pki/ca-trust/source/anchors"

    - name: Copy private key (0600)
      ansible.builtin.copy:
        src:  "{{ work_dir_ctrl }}/{{ item.subjectCN[0] }}.key"
        dest: "{{ key_dest }}"
        owner: root
        group: root
        mode: "0600"
      loop: "{{ expiring_list }}"
      loop_control:
        label: "{{ item.subjectCN[0] }}"

    - name: Copy certificate (0644)
      ansible.builtin.copy:
        src:  "{{ work_dir_ctrl }}/{{ item.subjectCN[0] }}.crt"
        dest: "{{ cert_dest }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ expiring_list }}"
      loop_control:
        label: "{{ item.subjectCN[0] }}"

    - name: Copy chain into trust anchors (0644)
      ansible.builtin.copy:
        src:  "{{ work_dir_ctrl }}/{{ item.subjectCN[0] }}-chain.crt"
        dest: "{{ chain_dest }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ expiring_list }}"
      loop_control:
        label: "{{ item.subjectCN[0] }}"

    - name: Restore SELinux contexts (RHEL-friendly)
      ansible.builtin.command: "restorecon -Rv /etc/pki"
      changed_when: true

    - name: Update system trust store
      ansible.builtin.command: "update-ca-trust"
      changed_when: true

    - name: Reload service if requested
      ansible.builtin.service:
        name: "{{ service_to_reload }}"
        state: reloaded
      when: service_to_reload | length > 0
